export const STATUS = {
    LOADING: 'LOADING',
    ERROR: 'ERROR',
    SUCCESS: 'SUCCESS'
};

export const ACTION_TYPE = {
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    FETCH_GIFS: 'FETCH_GIFS',
    FETCH_GIFS_PENDING: 'FETCH_GIFS_PENDING',
    FETCH_GIFS_FULFILLED: 'FETCH_GIFS_FULFILLED',
    FETCH_GIFS_REJECTED: 'FETCH_GIFS_REJECTED',
    LOAD_MORE_GIFS: 'LOAD_MORE_GIFS',
    LOAD_MORE_GIFS_PENDING: 'LOAD_MORE_GIFS_PENDING',
    LOAD_MORE_GIFS_FULFILLED: 'LOAD_MORE_GIFS_FULFILLED',
    LOAD_MORE_GIFS_REJECTED: 'LOAD_MORE_GIFS_REJECTED'
};

export const API_KEY = 'CdRKiCMbTnt9CkZTZ0lGukSczk6iT4Z6';
export const DEFAULT_LIMIT = 15;
export const GIFS_TRENDING_URL = 'https://api.giphy.com/v1/gifs/trending';
export const GIFS_SEARCH_URL = 'https://api.giphy.com/v1/gifs/search';
